enum SALE_STATUSES {
  PENDING = "PENDING",
  PARTIALLY_PAID = "PARTIALLY_PAID",
  PAID = "PAID",
  OVERDUE = "OVERDUE",
}

enum PAYMENT_METHODS {
  CASH = "CASH",
  BANK_TRANSFER = "BANK_TRANSFER",
  CHEQUE = "CHEQUE",
  ONLINE_PAYMENT = "ONLINE_PAYMENT",
}

enum BOOK_STATUSES {
  OPEN = "OPEN",
  CLOSED = "CLOSED",
}

export { SALE_STATUSES, PAYMENT_METHODS, BOOK_STATUSES };
